### ISSUE TITLE
Add checkbox for completing the task

### ISSUE THREAD

**Issue by shubham49** [shubham49/react-pwa#1]
Add check box before the task so that user can save his completed tasks

**Comment by angelamelinda** [comment]
May I take this?

**Comment by shubham49** [comment]
Yes you can

**Comment by angelamelinda** [comment]
Could you give me access to push my branch? I get 403 when I want to push my branch

**Comment by sparshs413** [comment]
@angelamelinda you will not get the access to this branch, instead, you need to fork this repo, make changes there and put up a pull request here, so that your code can be merged.

**Comment by angelamelinda** [comment]
I see, thank you @sparshs413 for the information.

**Comment by angelamelinda** [comment]
#8
