### ISSUE TITLE
Todo text validation before adding

### ISSUE THREAD

**Issue by arnabsen1729** [shubham49/react-pwa#11]
Currently there is not validation for the inputs. 
![image](https://user-images.githubusercontent.com/51032928/94431561-15b6b000-01b3-11eb-8631-94571e897b19.png)

@shubham49 Can you assign me this issue, I would love to contribute, also do assign the "Hacktoberfest" label. :smile:

**Comment by bhatvikrant** [comment]
Hey @shubham49 can you assign this to me? I ll be working on it

**Comment by arnabsen1729** [comment]
@bhatvikrant I am already working on it, also it is already assigned to me.

**Comment by bhatvikrant** [comment]
@arnabsen1729 my bad buddy

**Comment by arnabsen1729** [comment]
@bhatvikrant No issues :v:

**Comment by shubham49** [comment]
added in #15
