### ISSUE TITLE
[Feature Request] Adding multiline and markdown support for todos

### ISSUE THREAD

**Issue by arnabsen1729** [shubham49/react-pwa#12]
Currently users can only add a single line. We can add a feature where if the user presses `Shift + Enter` it will take them to the next line. Also we can add markdown support.

 `cause` **who** ~doesn't~ *love* Markdown :smile: 

@shubham49 can you please assign this issue to me

**Comment by arnabsen1729** [comment]
So I was working on the multiline addition,
So instead of just a simple string of text I am creating an array of text strings, each array will represent one todo, I was able to handle the event, but the only issue right now, is to change the input form. 

Like when I add another line by `Shift+Enter` the input form height should increase. Right now if you add something press shift enter the input form becomes blank. 
Any idea how to approach that @shubham49 i.e make the input form size depend on the input. 
![todo](https://user-images.githubusercontent.com/51032928/94788581-6582ba80-03f1-11eb-8399-592017e62c1e.gif)

**Comment by shubham49** [comment]
try using text area and we don't need to have array of texts. Use line separator for that.

**Comment by arnabsen1729** [comment]
@shubham49 yes, it is working. :smile:
